"""PDF Export for Storyboards - Professional industry-standard output."""
import os
import logging
from typing import List, Dict, Any
from PIL import Image
import io

logger = logging.getLogger(__name__)

def create_storyboard_pdf(
    shots: List[Dict[str, Any]], 
    project_name: str, 
    output_path: str,
    brief: str = ""
) -> str:
    """
    Creates a professional storyboard PDF with shot thumbnails, descriptions, and camera settings.
    """
    try:
        from reportlab.lib.pagesizes import A4, landscape
        from reportlab.lib import colors
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image as RLImage
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    except ImportError:
        logger.error("reportlab not installed. Run: pip install reportlab")
        return ""
    
    try:
        doc = SimpleDocTemplate(output_path, pagesize=landscape(A4))
        elements = []
        styles = getSampleStyleSheet()
        
        # Title style
        title_style = ParagraphStyle(
            'Title',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#8B3DFF'),
            spaceAfter=12
        )
        
        subtitle_style = ParagraphStyle(
            'Subtitle',
            parent=styles['Normal'],
            fontSize=10,
            textColor=colors.grey,
            spaceAfter=20
        )
        
        # Header
        elements.append(Paragraph(f"📽️ {project_name}", title_style))
        elements.append(Paragraph(f"Generated by MindLens | Powered by Bria FIBO", subtitle_style))
        if brief:
            elements.append(Paragraph(f"<b>Brief:</b> {brief[:200]}...", styles['Normal']))
        elements.append(Spacer(1, 20))
        
        # Create shot table data
        table_data = [['#', 'Shot', 'Description', 'Camera', 'Angle']]
        
        for i, shot in enumerate(shots):
            img_path = shot.get('image_path', '')
            desc = shot.get('description', f'Shot {i+1}')[:100]
            shot_type = shot.get('shot_type', 'Medium')
            angle = shot.get('camera_angle', 'Eye Level')
            
            # Create thumbnail if image exists
            if img_path and os.path.exists(img_path):
                try:
                    img = RLImage(img_path, width=1.5*inch, height=1*inch)
                except:
                    img = "No Image"
            else:
                img = "No Image"
            
            table_data.append([
                str(i + 1),
                img,
                Paragraph(desc, styles['Normal']),
                shot_type,
                angle
            ])
        
        # Create table
        table = Table(table_data, colWidths=[0.5*inch, 1.8*inch, 4*inch, 1.2*inch, 1.2*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#8B3DFF')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F8F7FF')),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#E5E7EB')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8F7FF')]),
        ]))
        
        elements.append(table)
        
        # Footer
        elements.append(Spacer(1, 30))
        elements.append(Paragraph("© MindLens - FIBO Hackathon 2024 | Product by Snigdha", subtitle_style))
        
        doc.build(elements)
        logger.info(f"PDF storyboard saved to {output_path}")
        return output_path
        
    except Exception as e:
        logger.error(f"Failed to create PDF: {e}")
        return ""


def get_shot_type_suggestions(scene_description: str) -> List[Dict[str, str]]:
    """
    AI-powered shot type suggestions based on scene description.
    Returns list of suggested shots with reasoning.
    """
    suggestions = []
    desc_lower = scene_description.lower()
    
    # Opening/establishing
    if any(word in desc_lower for word in ['enters', 'arrives', 'location', 'setting', 'room', 'place']):
        suggestions.append({
            "shot_type": "Establishing Shot",
            "reason": "Sets the scene and location for the audience",
            "camera": "Wide angle, static"
        })
    
    # Dialogue/conversation
    if any(word in desc_lower for word in ['says', 'speaks', 'talks', 'conversation', 'dialogue']):
        suggestions.append({
            "shot_type": "Over-the-Shoulder",
            "reason": "Classic dialogue coverage technique",
            "camera": "Medium shot, slight angle"
        })
        suggestions.append({
            "shot_type": "Close-up",
            "reason": "Captures emotional reactions during dialogue",
            "camera": "Tight framing on face"
        })
    
    # Action/movement
    if any(word in desc_lower for word in ['runs', 'fights', 'chases', 'action', 'moves', 'jumps']):
        suggestions.append({
            "shot_type": "Tracking Shot",
            "reason": "Follows the action dynamically",
            "camera": "Dolly or Steadicam"
        })
        suggestions.append({
            "shot_type": "Low Angle",
            "reason": "Makes action more dramatic and powerful",
            "camera": "Camera below subject"
        })
    
    # Emotion/tension
    if any(word in desc_lower for word in ['tense', 'scared', 'emotional', 'dramatic', 'intense']):
        suggestions.append({
            "shot_type": "Extreme Close-up",
            "reason": "Emphasizes emotional intensity",
            "camera": "Eyes or detail shots"
        })
        suggestions.append({
            "shot_type": "Dutch Angle",
            "reason": "Creates psychological tension",
            "camera": "Tilted frame"
        })
    
    # Romance/intimacy
    if any(word in desc_lower for word in ['love', 'romance', 'kiss', 'together', 'embrace', 'dance']):
        suggestions.append({
            "shot_type": "Two Shot",
            "reason": "Shows both characters in intimate space",
            "camera": "Medium shot, soft lighting"
        })
    
    # Default suggestions
    if not suggestions:
        suggestions = [
            {"shot_type": "Wide Shot", "reason": "Establishes context", "camera": "Full scene coverage"},
            {"shot_type": "Medium Shot", "reason": "Standard coverage", "camera": "Waist-up framing"},
            {"shot_type": "Close-up", "reason": "Emotional emphasis", "camera": "Face/detail focus"},
        ]
    
    return suggestions


def generate_mood_board_prompts(brief: str, character: str) -> List[str]:
    """
    Generates prompts for mood board images based on the brief and character.
    """
    prompts = []
    
    # Color/atmosphere prompt
    prompts.append(f"Color palette and atmosphere study: {brief[:100]}, cinematic mood board, color grading reference")
    
    # Character styling prompt
    if character:
        prompts.append(f"Character costume and styling reference: {character}, fashion mood board, cinematic")
    
    # Location/setting prompt
    prompts.append(f"Location and set design reference: {brief[:100]}, architectural mood board, production design")
    
    # Lighting reference
    prompts.append(f"Lighting reference: {brief[:100]}, cinematography lighting study, film still")
    
    return prompts


def create_project_package(
    project_name: str,
    project_dir: str,
    plan_dict: Dict[str, Any],
    outputs: List[Dict[str, Any]],
    settings: Dict[str, Any],
    reference_image_path: str = None,
    grid_path: str = None,
    output_zip_path: str = None
) -> str:
    """
    Creates a complete project package as a ZIP file containing:
    - All generated images
    - Reference images
    - Project settings (JSON)
    - Storyboard grid
    - Project metadata
    """
    import zipfile
    import json
    from datetime import datetime
    
    if not output_zip_path:
        output_zip_path = os.path.join(project_dir, f"{project_name}_package.zip")
    
    try:
        os.makedirs(os.path.dirname(output_zip_path), exist_ok=True)
        
        with zipfile.ZipFile(output_zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            
            # Add project metadata
            metadata = {
                "project_name": project_name,
                "created_at": datetime.now().isoformat(),
                "created_by": "MindLens - FIBO Continuity Director",
                "powered_by": "Bria FIBO API",
                "product_by": "Snigdha",
                "version": "1.0"
            }
            zipf.writestr("metadata.json", json.dumps(metadata, indent=2))
            
            # Add project plan
            zipf.writestr("project_plan.json", json.dumps(plan_dict, indent=2))
            
            # Add settings
            settings_data = {
                "pro_settings": settings,
                "fibo_parameters": {
                    "hdr_enabled": settings.get("hdr_enabled", True),
                    "bit_depth": settings.get("bit_depth", "16-bit"),
                    "lens_mm": settings.get("lens_mm", 50),
                    "camera_angle": settings.get("camera_angle", "eye_level"),
                    "composition": settings.get("composition", "rule_of_thirds")
                }
            }
            zipf.writestr("settings.json", json.dumps(settings_data, indent=2))
            
            # Add generated shots
            for i, output in enumerate(outputs):
                img_path = output.get("image_path", "")
                if img_path and os.path.exists(img_path):
                    zipf.write(img_path, f"shots/shot_{i+1:02d}.png")
            
            # Add reference image if exists
            if reference_image_path and os.path.exists(reference_image_path):
                ext = os.path.splitext(reference_image_path)[1]
                zipf.write(reference_image_path, f"references/character_ref{ext}")
            
            # Add storyboard grid if exists
            if grid_path and os.path.exists(grid_path):
                zipf.write(grid_path, "exports/storyboard_grid.png")
            
            # Add README
            readme_content = f"""# {project_name} - MindLens Project Package

## Project Overview
- **Created:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
- **Generated by:** MindLens - FIBO Continuity Director
- **Powered by:** Bria FIBO API

## Contents
- `metadata.json` - Project metadata
- `project_plan.json` - Full project plan with shot descriptions
- `settings.json` - Pro feature settings used
- `shots/` - All generated storyboard images
- `references/` - Character reference images
- `exports/` - Storyboard grid and exports

## Settings Used
- HDR: {settings.get('hdr_enabled', True)}
- Bit Depth: {settings.get('bit_depth', '16-bit')}
- Lens: {settings.get('lens_mm', 50)}mm
- Angle: {settings.get('camera_angle', 'eye_level')}

## Credits
Product by Snigdha | FIBO Hackathon 2024
"""
            zipf.writestr("README.md", readme_content)
            
            # Add shot list as CSV
            csv_content = "Shot #,Type,Angle,Description\n"
            for i, shot in enumerate(plan_dict.get("shots", [])):
                if isinstance(shot, dict):
                    csv_content += f"{i+1},{shot.get('shot_type', 'Medium')},{shot.get('camera_angle', 'eye_level')},\"{shot.get('description', '')[:100]}\"\n"
            zipf.writestr("shot_list.csv", csv_content)
        
        logger.info(f"Project package created: {output_zip_path}")
        return output_zip_path
        
    except Exception as e:
        logger.error(f"Failed to create project package: {e}")
        return ""


def create_project_document(
    project_name: str,
    brief: str,
    character: str,
    shots: List[Dict[str, Any]],
    settings: Dict[str, Any],
    outputs: List[Dict[str, Any]],
    reference_image_path: str = None,
    grid_path: str = None,
    output_path: str = None
) -> str:
    """
    Creates a complete project document as a Word file containing:
    - Project overview
    - Reference images (embedded)
    - Pro feature settings
    - All generated shots with descriptions
    - Storyboard grid
    """
    try:
        from docx import Document
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.enum.table import WD_TABLE_ALIGNMENT
    except ImportError:
        logger.error("python-docx not installed. Run: pip install python-docx")
        return ""
    
    from datetime import datetime
    
    try:
        doc = Document()
        
        # Title
        title = doc.add_heading(f'📽️ {project_name}', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Subtitle
        subtitle = doc.add_paragraph('MindLens - FIBO Continuity Director')
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        subtitle_run = subtitle.runs[0]
        subtitle_run.font.size = Pt(12)
        subtitle_run.font.color.rgb = RGBColor(139, 61, 255)
        
        doc.add_paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        doc.add_paragraph("Powered by Bria FIBO API | Product by Snigdha")
        doc.add_paragraph()
        
        # Brief Section
        doc.add_heading('📝 Project Brief', level=1)
        doc.add_paragraph(brief if brief else "No brief provided")
        doc.add_paragraph()
        
        # Character Section
        doc.add_heading('🎭 Character Description', level=1)
        doc.add_paragraph(character if character else "No character description provided")
        
        # Reference Image
        if reference_image_path and os.path.exists(reference_image_path):
            doc.add_paragraph()
            doc.add_paragraph("Character Reference Image:")
            try:
                doc.add_picture(reference_image_path, width=Inches(3))
            except:
                doc.add_paragraph("(Reference image could not be embedded)")
        doc.add_paragraph()
        
        # Pro Settings Section
        doc.add_heading('⚙️ Pro Feature Settings', level=1)
        
        settings_table = doc.add_table(rows=6, cols=2)
        settings_table.style = 'Table Grid'
        settings_data = [
            ("HDR Mode", "✅ Enabled" if settings.get("hdr_enabled", True) else "❌ Disabled"),
            ("Bit Depth", settings.get("bit_depth", "16-bit")),
            ("Lens", f"{settings.get('lens_mm', 50)}mm"),
            ("Camera Angle", settings.get("camera_angle", "eye_level")),
            ("Composition", settings.get("composition", "rule_of_thirds")),
            ("Total Shots", str(len(outputs)))
        ]
        for i, (label, value) in enumerate(settings_data):
            settings_table.rows[i].cells[0].text = label
            settings_table.rows[i].cells[1].text = value
        doc.add_paragraph()
        
        # Storyboard Grid
        if grid_path and os.path.exists(grid_path):
            doc.add_heading('🎬 Storyboard Overview', level=1)
            try:
                doc.add_picture(grid_path, width=Inches(6))
            except:
                doc.add_paragraph("(Storyboard grid could not be embedded)")
            doc.add_paragraph()
        
        # Individual Shots
        doc.add_heading('📸 Shot Breakdown', level=1)
        
        for i, output in enumerate(outputs):
            shot_data = shots[i] if i < len(shots) else {}
            if isinstance(shot_data, dict):
                desc = shot_data.get("description", f"Shot {i+1}")
                shot_type = shot_data.get("shot_type", "Medium")
                angle = shot_data.get("camera_angle", "eye_level")
            else:
                desc = f"Shot {i+1}"
                shot_type = "Medium"
                angle = "eye_level"
            
            doc.add_heading(f'Shot {i+1}: {shot_type}', level=2)
            doc.add_paragraph(f"Camera Angle: {angle}")
            doc.add_paragraph(f"Description: {desc}")
            
            img_path = output.get("image_path", "")
            if img_path and os.path.exists(img_path):
                try:
                    doc.add_picture(img_path, width=Inches(4))
                except:
                    doc.add_paragraph("(Image could not be embedded)")
            doc.add_paragraph()
        
        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph("© MindLens - FIBO Hackathon 2024 | Product by Snigdha")
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Save
        if not output_path:
            output_path = f"{project_name}_project.docx"
        
        os.makedirs(os.path.dirname(output_path), exist_ok=True) if os.path.dirname(output_path) else None
        doc.save(output_path)
        logger.info(f"Project document saved to {output_path}")
        return output_path
        
    except Exception as e:
        logger.error(f"Failed to create project document: {e}")
        return ""
